### ISSUE TITLE
Tox -rvv py35 py36 py37 py39 

### ISSUE THREAD

**Issue by ghost** [tompin/multicrypto#7]
Errors test_$$$$$$$$.py

pytest

Error: "_sqlite3"

**Comment by tompin** [comment]
This looks like some environment issue, it is too little information to reproduce (system details and reproduction steps are missing). Please notice that python 3.5 is not supported. Here you can find all steps to run test for each supported python version:
https://travis-ci.org/github/tompin/multicrypto

**Comment by ghost** [comment]
sometimes it generates error sometimes not
what to do?

pytest @betagamma
================================================= test session starts ==================================================
platform linux -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /mnt/c/Users/dell/Downloads/bitcoin-hacking-tools-master/private-key-harvesters/brainflayer/multicrypto
plugins: cov-2.6.0
collected 186 items

tests/test_address.py ...........                                                                                [  5%]
tests/test_base58.py ...................................                                                         [ 24%]
tests/test_bech32.py ..................................                                                          [ 43%]
tests/test_checkaddress.py ....                                                                                  [ 45%]
tests/test_coins.py ..                                                                                           [ 46%]
tests/test_ellipticcurve.py ..................                                                                   [ 55%]
tests/test_ethaddress.py ......                                                                                  [ 59%]
tests/test_genaddress.py ..................                                                                      [ 68%]
tests/test_network.py .                                                                                          [ 69%]
tests/test_numbertheory.py ........................                                                              [ 82%]
tests/test_sendcrypto.py .                                                                                       [ 82%]
tests/test_signmessage.py .                                                                                      [ 83%]
tests/test_sweepaddress.py .                                                                                     [ 83%]
tests/test_transaction.py .........                                                                              [ 88%]
tests/test_transaddress.py .                                                                                     [ 89%]
tests/test_transprivkey.py .                                                                                     [ 89%]
tests/test_utils.py ............                                                                                 [ 96%]
tests/test_validators.py ......                                                                                  [ 99%]
tests/test_verifymessage.py .                                                                                    [100%]

=================================================== warnings summary ===================================================
../../../../../../../../../usr/local/lib/python3.9/site-packages/responses.py:139
../../../../../../../../../usr/local/lib/python3.9/site-packages/responses.py:139
../../../../../../../../../usr/local/lib/python3.9/site-packages/responses.py:139
../../../../../../../../../usr/local/lib/python3.9/site-packages/responses.py:139
../../../../../../../../../usr/local/lib/python3.9/site-packages/responses.py:139
  /usr/local/lib/python3.9/site-packages/responses.py:139: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
    signature = inspect.formatargspec(args, a, kw, defaults)

../../../../../../../../../usr/local/lib/python3.9/site-packages/responses.py:143
../../../../../../../../../usr/local/lib/python3.9/site-packages/responses.py:143
../../../../../../../../../usr/local/lib/python3.9/site-packages/responses.py:143
../../../../../../../../../usr/local/lib/python3.9/site-packages/responses.py:143
../../../../../../../../../usr/local/lib/python3.9/site-packages/responses.py:143
  /usr/local/lib/python3.9/site-packages/responses.py:143: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
    callargs = inspect.formatargspec(args, a, kw, None)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================================== 186 passed, 10 warnings in 5.48s ===========================================


















next command tox -vv

================================================= test session starts ==================================================
platform linux -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
cachedir: .tox/py39/.pytest_cache
rootdir: /mnt/c/Users/dell/Downloads/bitcoin-hacking-tools-master/private-key-harvesters/brainflayer/multicrypto
collected 177 items / 5 errors / 172 selected

======================================================== ERRORS ========================================================
_____________________________________ ERROR collecting tests/test_checkaddress.py ______________________________________
ImportError while importing test module '/mnt/c/Users/dell/Downloads/bitcoin-hacking-tools-master/private-key-harvesters/brainflayer/multicrypto/tests/test_checkaddress.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_checkaddress.py:6: in <module>
    import responses
E   ModuleNotFoundError: No module named 'responses'
_________________________________________ ERROR collecting tests/test_coins.py _________________________________________
ImportError while importing test module '/mnt/c/Users/dell/Downloads/bitcoin-hacking-tools-master/private-key-harvesters/brainflayer/multicrypto/tests/test_coins.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_coins.py:1: in <module>
    import validators
E   ModuleNotFoundError: No module named 'validators'
________________________________________ ERROR collecting tests/test_network.py ________________________________________
ImportError while importing test module '/mnt/c/Users/dell/Downloads/bitcoin-hacking-tools-master/private-key-harvesters/brainflayer/multicrypto/tests/test_network.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_network.py:1: in <module>
    import responses
E   ModuleNotFoundError: No module named 'responses'
______________________________________ ERROR collecting tests/test_sendcrypto.py _______________________________________
ImportError while importing test module '/mnt/c/Users/dell/Downloads/bitcoin-hacking-tools-master/private-key-harvesters/brainflayer/multicrypto/tests/test_sendcrypto.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_sendcrypto.py:5: in <module>
    import responses
E   ModuleNotFoundError: No module named 'responses'
_____________________________________ ERROR collecting tests/test_sweepaddress.py ______________________________________
ImportError while importing test module '/mnt/c/Users/dell/Downloads/bitcoin-hacking-tools-master/private-key-harvesters/brainflayer/multicrypto/tests/test_sweepaddress.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_sweepaddress.py:5: in <module>
    import responses
E   ModuleNotFoundError: No module named 'responses'
=============================================== short test summary info ================================================
ERROR tests/test_checkaddress.py
ERROR tests/test_coins.py
ERROR tests/test_network.py
ERROR tests/test_sendcrypto.py
ERROR tests/test_sweepaddress.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================== 5 errors in 0.64s ===================================================
ERROR: InvocationError for command '/mnt/c/Users/dell/Downloads/bitcoin-hacking-tools-master/private-key-harvesters/brainflayer/multicrypto/.tox/py39/bin/pytest' (exited with code 2)
py39 finish: runtests after 1.42 seconds
py39 start: run-test-post
py39 finish: run-test-post after 0.00 seconds
_______________________________________________________ summary ________________________________________________________
ERROR:   py36: commands failed
ERROR:   py37: commands failed
ERROR:   py38: commands failed
ERROR:   py39: commands failed
cleanup /mnt/c/Users/dell/Downloads/bitcoin-hacking-tools-master/private-key-harvesters/brainflayer/multicrypto/.tox/.tmp/package/1/multicrypto-0.1.14.zip


help me for wsl.exe 
{
                               BUT I'M really not a PROGRAMMER.. :o
}

**Comment by ghost** [comment]
Hello tommy! I wanted to became hacker..but it really doesnt possible for me because i really like using programs created by programmers really like you...and i want money like btc (illegal in my country).

**Comment by ghost** [comment]
multicrypto# pytest @betagamma
================================================= test session starts ==================================================platform linux -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /
plugins: cov-2.6.0
collected 6279 items / 1 error / 14 skipped / 6264 selected

======================================================== ERRORS ========================================================_________________________________ ERROR collecting Python-3.9.1/Lib/test/test_capi.py __________________________________/usr/local/lib/python3.9/site-packages/_pytest/runner.py:311: in from_call
    result: Optional[TResult] = func()
/usr/local/lib/python3.9/site-packages/_pytest/runner.py:341: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
/usr/local/lib/python3.9/site-packages/_pytest/unittest.py:87: in collect
    yield TestCaseFunction.from_parent(self, name=name, callobj=funcobj)
/usr/local/lib/python3.9/site-packages/_pytest/python.py:1619: in from_parent
    return super().from_parent(parent=parent, **kw)
/usr/local/lib/python3.9/site-packages/_pytest/nodes.py:190: in from_parent
    return cls._create(parent=parent, **kw)
/usr/local/lib/python3.9/site-packages/_pytest/nodes.py:94: in _create
    return super().__call__(*k, **kw)
/usr/local/lib/python3.9/site-packages/_pytest/python.py:1582: in __init__
    self.keywords.update(self.obj.__dict__)
E   AttributeError: 'builtin_function_or_method' object has no attribute '__dict__'
=================================================== warnings summary ===================================================Python-3.9.1/Lib/distutils/tests/test_dist.py:32
  /mnt/c/Users/dell/Downloads/bitcoin-hacking-tools-master/private-key-harvesters/brainflayer/multicrypto/Python-3.9.1/Lib/distutils/tests/test_dist.py:32: PytestCollectionWarning: cannot collect test class 'TestDistribution' because it has a __init__ constructor (from: Python-3.9.1/Lib/distutils/tests/test_dist.py)
    class TestDistribution(Distribution):

../../../../../../../../../usr/local/lib/python3.9/importlib/__init__.py:127
  /usr/local/lib/python3.9/importlib/__init__.py:127: PendingDeprecationWarning: lib2to3 package is deprecated and may not be able to parse Python 3.10+
    return _bootstrap._gcd_import(name[level:], package, level)

Python-3.9.1/Lib/test/test_argparse.py:3118
  /mnt/c/Users/dell/Downloads/bitcoin-hacking-tools-master/private-key-harvesters/brainflayer/multicrypto/Python-3.9.1/Lib/test/test_argparse.py:3118: PytestCollectionWarning: cannot collect test class 'TestHelpFormattingMetaclass' because it has a __init__ constructor (from: Python-3.9.1/Lib/test/test_argparse.py)
    class TestHelpFormattingMetaclass(type):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=============================================== short test summary info ================================================ERROR Python-3.9.1/Lib/test/test_capi.py::Test_testcapi - AttributeError: 'builtin_function_or_method' object has no ...!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!====================================== 14 skipped, 3 warnings, 1 error in 28.21s =======================================root@DESKTOP-KB7UK66:/# pip install multicrypto
Requirement already satisfied: multicrypto in /usr/local/lib/python3.9/site-packages/multicrypto-0.1.14-py3.9.egg (0.1.14)
Requirement already satisfied: pysha3==1.0.2 in /usr/local/lib/python3.9/site-packages/pysha3-1.0.2-py3.9-linux-x86_64.egg (from multicrypto) (1.0.2)
Requirement already satisfied: Pillow==8.1.0 in /usr/local/lib/python3.9/site-packages (from multicrypto) (8.1.0)
Requirement already satisfied: qrcode==6.1 in /usr/local/lib/python3.9/site-packages/qrcode-6.1-py3.9.egg (from multicrypto) (6.1)
Requirement already satisfied: six in /usr/local/lib/python3.9/site-packages/six-1.15.0-py3.9.egg (from qrcode==6.1->multicrypto) (1.15.0)
Collecting requests==2.25.1 (Wtf.. IS THIS REQUIRING 2.25.1 EXCEPT BLACK hats WANTS 2.25.0 etc....)
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)  
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.9/site-packages/idna-2.10-py3.9.egg (from requests==2.25.1->multicrypto) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages/certifi-2020.12.5-py3.9.egg (from requests==2.25.1->multicrypto) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/site-packages/urllib3-1.26.2-py3.9.egg (from requests==2.25.1->multicrypto) (1.26.2)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.9/site-packages (from requests==2.25.1->multicrypto) (3.0.4)
Installing collected packages: requests
  Attempting uninstall: requests
    Found existing installation: requests 2.25.0
    Uninstalling requests-2.25.0:
      Successfully uninstalled requests-2.25.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bitcoinlib 0.5.1.post1 requires requests==2.25.0, but you have requests 2.25.1 which is incompatible.
Successfully installed requests-2.25.1
root@DESKTOP-KB7UK66: genaddress
usage: genaddress [-h] [-p PATTERN] -s SYMBOL [-i INPUT_SCRIPT] [-c CORES] [-u] [-w] [-d OUTPUT_DIR]
genaddress: error: the following arguments are required: -s/--symbol
root@DESKTOP-0007: genaddress -h
usage: genaddress [-h] [-p PATTERN] -s SYMBOL [-i INPUT_SCRIPT] [-c CORES] [-u] [-w] [-d OUTPUT_DIR]

Multi coin vanity generation script

optional arguments:
  -h, --help            show this help message and exit
  -p PATTERN, --pattern PATTERN
                        Pattern which generated address should contain
  -s SYMBOL, --symbol SYMBOL
                        Symbol of the coin i.e. BTC
  -i INPUT_SCRIPT, --input_script INPUT_SCRIPT
                        Generate address based on input script for P2SH transactions
  -c CORES, --cores CORES
                        How many cores we would like to use. Default 1 core.
  -u, --uncompressed    Generate address based on uncompressed wif private key format
  -w, --segwit          Generate segwit (P2SH-P2WPKH) address
  -d OUTPUT_DIR, --output_dir OUTPUT_DIR
                        Directory where QR codes with address and private key will be stored
root@DESKTOP-# ls
 setup.py  tox.ini README.md         dist   multicrypto.egg-info  requirements.txt  setup.cfg             tests     venv
root@DESKTOP-007# genaddress -h
usage: genaddress [-h] [-p PATTERN] -s SYMBOL [-i INPUT_SCRIPT] [-c CORES] [-u] [-w] [-d OUTPUT_DIR]

Multi coin vanity generation script

optional arguments:
  -h, --help            show this help message and exit
  -p PATTERN, --pattern PATTERN
                        Pattern which generated address should contain
  -s SYMBOL, --symbol SYMBOL
                        Symbol of the coin i.e. BTC
  -i INPUT_SCRIPT, --input_script INPUT_SCRIPT
                        Generate address based on input script for P2SH transactions
  -c CORES, --cores CORES
                        How many cores we would like to use. Default 1 core.
  -u, --uncompressed    Generate address based on uncompressed wif private key format
  -w, --segwit          Generate segwit (P2SH-P2WPKH) address
  -d OUTPUT_DIR, --output_dir OUTPUT_DIR
                        Directory where QR codes with address and private key will be stored
root@DESKTOP-007# genaddress -w
usage: genaddress [-h] [-p PATTERN] -s SYMBOL [-i INPUT_SCRIPT] [-c CORES] [-u] [-w] [-d OUTPUT_DIR]
genaddress: error: the following arguments are required: -s/--symbol
root@DESKTOP-007# genaddress -w -s BTC
Looking for pattern  for bitcoin using 1 workers
Address: 3JqoZ412eLPGBVzGD5Q3LcApeDENWyGP9q
Private key: KxNPf7tz1VgfmvpGzgd1Vh3hE4ThNkw72kK3YRiDRELRMtrgshJ1



hehe i installed it myself...give me 1 coffee
